### ISSUE TITLE
Possible bug in Data Types Exercise 2?

### ISSUE THREAD

**Issue by joelneely** [svtk/AtomicKotlinCourse#22]
Thanks for the course!

Exercise 2 of Data Types asks for "**the** name of **the type** that can't be combined with itself using +" (singular) and expects an answer of Boolean. However, Kotlin also rejects character + character, so shouldn't the question and answer be plural, to include both Boolean and Char?

**Comment by svtk** [comment]
Thanks for noticing that, that's right! I've simplified this task a bit to remove this question (now it might be confusing given there're two options and it's not that important in the end). https://github.com/svtk/AtomicKotlinCourse/commit/291998f29232f43f38c9deac8c027bade1e3628f
