### ISSUE TITLE
Confusing text or typos in _ and Number Types Exercise 2

### ISSUE THREAD

**Issue by joelneely** [svtk/AtomicKotlinCourse#23]
Thanks for the course!

The wording of the instructions for String Templates Exercise 5 is a bit confusing on first reading. The last sentence says:

> Rename the val name to result without renaming "answer" in the string literal.

But the val name (answer) inside the String template _should_ be changed without changing the caption "The answer is" before it. Perhaps is is the word "renaming" near the end of the sentence that is confusing, and it could read something like the following with less opportunity for confusion.

> Rename the val name to result without changing the word "answer" in the rest of the string template.

Also, the instructions for Number Types Exercise 2 seems to contain a typo, with an extra '^' character at the end of each expression. For example, the first bulleted item reads "A million (10^6^)" but if the reader is supposed to interpret '^' as exponentiation, the second occurrence would be invalid. (If that should be markup to format the '6' as a superscript, it is not being displayed that way in the GUI.)

**Comment by BruceEckel** [comment]
Thanks, Joel!

Svetlana, I assume you're automatically seeing these reports, is that
correct?


*Bruce Eckel*
MindViewLLC.com
Blog: BruceEckel.com
EvolveWork.co
WinterTechForum.com <http://www.WinterTechForum.com>
OnJava8.com <http://www.OnJava8.com>
www.AtomicKotlin.com
Reinventing-Business.com <http://www.Reinventing-Business.com>

**Comment by svtk** [comment]
Yes. Thank you for the feedback! I've updated the wording for 'String Templates Ex 5' description: https://github.com/svtk/AtomicKotlinCourse/commit/b1f2ec21684abb1fa06dd23d7e4c1fcbeb6629db.

**Comment by svtk** [comment]
It was indeed intended to be a markdown superscript font (which probably stopped working for some reason). I've replaced it with HTML tags: https://github.com/svtk/AtomicKotlinCourse/commit/f0278aa901fcf7f3c8d277a440bdb4c98aeb0065. Thanks for pointing it out!
