### ISSUE TITLE
Possible "bug" in description for Looping and Ranges Examples

### ISSUE THREAD

**Issue by joelneely** [svtk/AtomicKotlinCourse#24]
Page 62 of the AtomicKotlin PDF, between the comments for the IndexIntoString and AddingIntToChar exercises, contains a statement beginning:

> Characters are stored as numbers corresponding to their ASCII codes...

However, previous Java/JVM experience as confirmed by experiments modifying the IndexIntoString demo, suggests that characters (`Char` data) are in Unicode. While the familiar characters (e.g. digits and Roman alphabet) have similar codes in ASCII and Unicode, would it be better to clarify that the numeric codes are Unicode?

An expanded version of the example:

```
fun main() {
  val s = "abc∂π"
  println("Unpacking \"$s\"\n")
  for (i in 0..s.lastIndex) {
    val c = s[i]
    println("$c (${c.toInt()}) is followed by ${c + 1}")
  }
}
```

provides output that wouldn't be explained by ASCII.

```
Unpacking "abc∂π"

a (97) is followed by b
b (98) is followed by c
c (99) is followed by d
∂ (8706) is followed by ∃
π (960) is followed by ρ
```

**Comment by BruceEckel** [comment]
Thanks, Joel. Modified two places in the book source. @svtk this needs modification in the exercises/solutions, I think.

**Comment by svtk** [comment]
Thanks! Fixed it in the task description https://github.com/svtk/AtomicKotlinCourse/commit/f9371000aacfa6e2414cbc848fc2a6ff62895551
