### ISSUE TITLE
Error in instructions for Creating Classes Exercise 4

### ISSUE THREAD

**Issue by joelneely** [svtk/AtomicKotlinCourse#26]
The instructions for Creating Classes Exercise 4 state:

> Put the caret on the `String` type and its `get()` and `length()` member functions, then use `Quick Documentation`.

The code in the exercise doesn't contain either of those, so presumably the student is expected to add statements containing them inside `main()`.

However, attempting to reference `s.length()` yields an error, and `Quick Documentation` only shows `No documentation found.` as Kotlin treats `length` as a `public val` and _not_ as a member function. Are the instructions intended to cause the student to make an error and then figure it out?

**Comment by svtk** [comment]
Thanks for pointing this out! No, it was a mistake: the function names haven't been updated in the code. Should be "Put the caret on the String type and its toUpperCase() and toLowerCase() member functions" (soon will be updated)
